apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chaewonzz # default
spec:
  type: NodePort
  selector:
    app: edu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
